{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "provenance": [],
      "authorship_tag": "ABX9TyP/OQ5o9W75gqdSWHEi3wqx",
      "include_colab_link": true
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "view-in-github",
        "colab_type": "text"
      },
      "source": [
        "<a href=\"https://colab.research.google.com/github/rishikeshsingh08662-ai/atm-machine-project/blob/main/student_management%20system.py\" target=\"_parent\"><img src=\"https://colab.research.google.com/assets/colab-badge.svg\" alt=\"Open In Colab\"/></a>"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {
        "id": "wg76DyssigkB"
      },
      "outputs": [],
      "source": [
        "# features\n",
        "# add student\n",
        "# view student\n",
        "# search student\n",
        "# delete student\n",
        "# update student\n",
        "# exit\n",
        "print(\"----welcome to student details project----\")\n",
        "save = []\n",
        "while True:\n",
        "    print(\"1. add student\")\n",
        "    print(\"2. view student\")\n",
        "    print(\"3. delete student\")\n",
        "    print(\"4. search student\")\n",
        "    print(\"5. update student\")\n",
        "    print(\"6. exit\")\n",
        "\n",
        "    choice = input(\"Enter your choice:\")\n",
        "\n",
        "    # ADD STUDENTS\n",
        "\n",
        "    if choice == '1':\n",
        "        name = input(\"Enter student name:\")\n",
        "        school = input(\"Enter school name:\")\n",
        "        age = input(\"Enter age:\")\n",
        "        aim = input(\"Enter aim:\")\n",
        "\n",
        "        student = {\n",
        "            \"name\": name,\n",
        "            \"school\": school,\n",
        "            \"age\": age,\n",
        "            \"aim\": aim\n",
        "        }\n",
        "        save.append(student)\n",
        "        print(\"student added successfully\")\n",
        "\n",
        "        # VIEW STUDENT\n",
        "\n",
        "    elif choice == '2':\n",
        "        if len(save) == 0:\n",
        "            print(\"student detail empty!!\")\n",
        "        else:\n",
        "            print(\"student detail open!!\")\n",
        "            for i, student in enumerate(save, start=1):\n",
        "                print(f\"{i}. {student}\")\n",
        "\n",
        "    # DELETED STUDENT\n",
        "    elif choice == '3':\n",
        "        if len(save) == 0:\n",
        "            print(\"student not delete!!\")\n",
        "        else:\n",
        "            print(\"student detail!!\")\n",
        "            for i, student in enumerate(save, start=1):\n",
        "                print(f\"{i}. {student}\")\n",
        "            number = int(input(\"Enter student number:\"))\n",
        "\n",
        "            if 1 <= number <= len(save):\n",
        "                removed = save.pop(number - 1)\n",
        "                print(f\"'{removed}' deleted successfully\")\n",
        "            else:\n",
        "                print(\"invalid student number!!\")\n",
        "\n",
        "    # SEARCH STUDENT\n",
        "    elif choice == '4':\n",
        "        if len(save) == 0:\n",
        "            print(\"student not found!!\")\n",
        "        else:\n",
        "            search_name = input(\"Enter student name:\")\n",
        "\n",
        "            found = False\n",
        "\n",
        "            for student in save:\n",
        "                if student [\"name\"].lower() == search_name.lower():\n",
        "                    print(\"student found!!\")\n",
        "                    print(student)\n",
        "                    found = True\n",
        "                    break\n",
        "            if not found:\n",
        "                print(\"student not found!!\")\n",
        "\n",
        "    # UPDATE STUDENT\n",
        "    elif choice == '5':\n",
        "        if len(save) == 0:\n",
        "            print(\"student not found!!\")\n",
        "        else:\n",
        "            print(\"student detail\")\n",
        "            for i, student in enumerate(save, start=1):\n",
        "                print(f\"{i}. {student}\")\n",
        "            number = int(input(\"Enter student number:\"))\n",
        "            if 1 <= number <= len(save):\n",
        "                save[number - 1][\"name\"] = input(\"Enter new name:\")\n",
        "                save[number - 1][\"school\"] = input(\"Enter new school name:\")\n",
        "                save[number - 1][\"age\"] = input(\"Enter new age:\")\n",
        "                save[number - 1][\"aim\"] = input(\"Enter new aim:\")\n",
        "                print(\"student updated successfully\")\n",
        "            else:\n",
        "                print(\"invalid student number!!\")\n",
        "\n",
        "    # EXIT THE PROJECT\n",
        "    elif choice == '6':\n",
        "        print(\"thanks for using student management detail project!!\")\n",
        "        break\n",
        "\n",
        "    # INVALID CHOICE\n",
        "    else:\n",
        "        print(\"invalid choice!!\")\n",
        "\n",
        "\n",
        "\n"
      ]
    }
  ]
}