# -*- coding: utf-8 -*-
"""Untitled10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Id6lb9YHoqaSUl_TA2pswWIj-J9TMMQG
"""

# project no 8
# Atm machine project
print('welcome to atm machine!')
correct_account_no = '333sachin44334'
correct_pin_no= '9988'
balance = 2500
mini_statement = []
attempt = 0

while True:
    try:
        account_no = input('Enter your account number:')
        pin_no = input('Enter your pin number:')
    except ValueError:
        print('please enter valid input')
        continue

    if account_no == correct_account_no and pin_no == correct_pin_no:
        print('welcome!!')
        attempt = 0
        while True:
            print('----MENU----')
            print('1. check balance')
            print('2. withdraw money')
            print('3. deposit money')
            print('4. mini_statement')
            print('5. pin change')
            print('6. exit')

            choice = input('Enter your choice:')

            if choice == '1':
                print('your balance is:',balance)
                mini_statement.append(f"check balance:{balance}")


            elif choice == '2':
                try:
                    withdraw_money = int(input('Enter your withdraw money:'))
                except ValueError:
                    print('please enter numbers only!')
                    continue

                if withdraw_money > 0 and withdraw_money <= balance:
                    balance = balance - withdraw_money
                    mini_statement.append(f"check withdraw:{withdraw_money}")

                    print('please collect your cash:')
                    print('remaining balance',balance)
                elif withdraw_money <= 0:
                    print('please enter a valid amount!')
                else:
                    print('insufficient money!!')

            elif choice == '3':
                try:
                    deposit_money = int(input('Enter your deposit money:'))
                except ValueError:
                    print('please enter numbers only!')
                    continue

                if deposit_money > 0:
                    balance = balance + deposit_money
                    mini_statement.append(f"check deposit:{deposit_money}")
                    print('money deposit successfully!')
                    print('current balance',balance)
                else:
                    print('please enter a valid amount!')

            elif choice == '4':
                print('----mini_statement----')
                if mini_statement:
                    for i in mini_statement:
                        print(i)
                else:
                    print('no money transactions!!')
            elif choice == '5':
                old_pin_no = input('Enter your old pin_no:')
                if old_pin_no == correct_pin_no:
                    new_pin_no = input('Enter your new pin_no:')
                    confirm_pin_no = input('Enter your confirm pin_no:')
                    if new_pin_no == confirm_pin_no:
                        correct_pin_no = new_pin_no
                        print('new pin change successfully!')
                        mini_statement.append('pin changed')
                    else:
                        print('new pin_no and confirm pin_no do not match!')
                else:
                    print('old pin wrong')

            elif choice == '6':
                print('thanks for using atm machine!')
                break
            else:
                print('wrong choice!')
        break
    elif account_no == correct_account_no and pin_no != correct_pin_no:
        attempt += 1
        print('wrong pin number!')
    elif account_no != correct_account_no and pin_no == correct_pin_no:
        attempt += 1
        print('wrong account number!')
    else:
        attempt += 1
        print('both account no and pin number are wrong!')
    if attempt == 3:
        print('you enter wrong details many times!')
        print('try again! 24 hours!')
        break
    else:
        print('remaining attempt',3 - attempt)

# project no 7
import random
import hangman_stage
word_list = ["hello","wao","wonderful"]
lives=5
chosen_word = random.choice(word_list)
print(chosen_word)
display = []
for i in range(len(chosen_word)):
    display += '_'
print(display)
game_over=False
while not game_over:
    guessed_letter=input("Guess a letter:").lower()
    for position in range(len(chosen_word)):
        letter = chosen_word[position]
        if letter == guessed_letter:
            display[position]= guessed_letter
    print(display)
    if guessed_letter not in chosen_word:
        lives -= 1
        print(f"{lives}")
        if lives == 0:
            game_over = True
            print("You lose!!")
    print(display)
    print(hangman_stage.stage[lives])

    if '_' not in display:
        game_over = True
        print("You win!!")

# project no 6
def calculator():
print("welcome to python calculator")

While True:
    print("\n---Menu---")
    print("1. Add (+)")
    print("2. sub (-)")
    print("3. mul (*)")
    print("4. divide (/)")
    print("5. module (//)")
    print("6. exponent (**)")
    print("7. exit(calculator band kre)")

    choice = input("\nApne option chune(1-7):")

    if choice = '7':
        print("\n calculator ko use krne ke thanks!!Good bye")
        break

    if choice = ['1','2','3','4','5','6']:
        try:
        number1 = float(("first number type"))
        number2 = float(input("second number type"))
        except value error:
            print("galat input only with no type!!")
            continue:

        #operation ka logic
        if choice == '1':
            print("number1 + number2")
        elif choice == '2':
            print("number1 - number2")
        elif choice == '3':
            print("number1 * number2")
        elif choice == '4':
            if num2 != 0:
                print("number1 / number2")
            else:
                print("0 se divide nahi de sakte")
        elif choice == '5':
            if num2 != 0:
                print("number1 % number2")
            else:
                print("0 se module nahi nikal sakte")
        else:
            print("galat option please chose the no 1-7")
calculator()

# project 5 (password created)
# easy password

import random
letters = ['a','b','d','e','d','e','t','b','m','n','o','p','q','r','u','y','i','w','f','z','x']
numbers = ['4','6','7','89','65','5','44','0','3','9','33','09']
symbols = [',','.','#','%','*','@','!','*']

#Taking input
sa_letters = int(input("How many letters would you like in your password?/n:"))
sa_numbers = int(input("How many numbers would you like?/n:"))
sa_symbols = int(input("How many symbols would you like?/n:"))
'''
for char in range(0,sa_letters):
  password += random.choice(letters)

for char in range(0,sa_numbers):
  password += random.choice(numbers)

for char in range(0,sa_symbols):
  password += random.choice(symbols)

print(f" your final password {password}")
'''

#hard level password

password_list = []

for char in range(0,sa_letters):
  password_list.append(random.choice(letters))

for char in range(0,sa_symbols):
  password_list.append(random.choice(symbols))

for char in range(0,sa_numbers):
  password_list.append(random.choice(numbers))

print(password_list)
random.shuffle(password_list)
print(password_list)

password = ""
for char in password_list:
  password += char
print(f" your password is:{password}")

# project no 4
#pizza delivers
print("Welcome to pizza delivers!")

#taking input
size = input("What size pizza do you want? S, M or L: ")
bill = 0
if size == "S":
  bill += 15
elif size == "M":
  bill += 20
elif size == "L":
  bill += 25
else:
    print("you wrong input type")
#taking input
pepperoni = input("Do you want pepperoni on your pizza? Y or N:")
if pepperoni == "Y":
  bill += 2
else :
  print("koi baat nhi")
#taking input
extra_cheese = input("Do you want extra_cheese? Y or N")
if extra_cheese == "Y":
  bill += 1
print(f" your final bill is:{bill}.")

# project 3 (rock paper scissors game(game is playing with computer and player:))
import random
rock = 0
paper = 1
scissors = 2

computer_choice = random.randint(0,2)
user_choice = int(input("types of user:"))
print("computer_choice:",computer_choice)

#conditional statement

if user_choice == computer_choice:
  print("match drow")
elif user_choice == rock and computer_choice == scissors:
  print("you win")
elif user_choice == scissors and computer_choice == paper:
  print("you win")
elif user_choice == paper and computer_choice == rock:
  print("you win")
else:
  if user_choice >2:
    print("you lose")
  elif computer_choice <2:
    print("you lose")
  else:
    print("you lose type for invalid no")

# project 2
def routine():
  while True:
    print("---timing---")
    print("7 to 9")
    print("9 to 9:30")
    print("9:30 to 10")
    print("10 to 12")
    print("12 to 2")
    print("2 to 4")
    print("4 to 6")
    print("6 to 7")
    print("7:00 to 9:00")
    print("11.exit:")

    choice = input("type timing:")

    if choice == '11':
      print("aise hi padhte rho,today work is done")
      break

    if choice in ['1','2','3','4','5','6','7','8','9','10']:
      try:
        timing=input("type any no")
      except ValueError:
          print("galat input nahi only no type")
          continue

    if choice == '7 to 9':
      print("python padhna hai")
    elif choice == '9 to 9:30':
      print("nasta krna hai abhi")
    elif choice == '9:30 to 10':
      print("jo python padha h uspar project ka sochna")
    elif choice == '10 to 12':
      print("maths padhna hai")
    elif choice == '12 to 2':
      print("maths jo padha hai usko revision kro or jo samay bacha hai uska or padhao")
    elif choice == '2 to 4':
      print("python project")
    elif choice == '4 to 6':
      print("python me logic build")
    elif choice == '6 to 7':
      print("dukan pe jana hai")
    elif choice == '7 to 9':
      work = "english padhna hai"
    else:
      print("sahi no type kijeye jisse me apko bta sku ki kya padhna hai")

    while True:
      status = input("kya apne ye work complete kr liya(yes or no):").strip().lower()

      if status == 'yes':
        print("bahut badhiya ab age ka kaam shru kr sakte hai")
        break
      elif status == 'no':
        print("pahle ka kaam pura kijeye")
      else:
        print("galat input please sirf 'yes or no' likhe")
routine()