# -*- coding: utf-8 -*-
"""Untitled53.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Y5A98_Q-TtNrSDHatKXUpjbz_OLX3IpN
"""

# features
# add student
# view student
# search student
# delete student
# update student
# exit
print("----welcome to student details project----")
save = []
while True:
    print("1. add student")
    print("2. view student")
    print("3. delete student")
    print("4. search student")
    print("5. update student")
    print("6. exit")

    choice = input("Enter your choice:")

    # ADD STUDENTS

    if choice == '1':
        name = input("Enter student name:")
        school = input("Enter school name:")
        age = input("Enter age:")
        aim = input("Enter aim:")

        student = {
            "name": name,
            "school": school,
            "age": age,
            "aim": aim
        }
        save.append(student)
        print("student added successfully")

        # VIEW STUDENT

    elif choice == '2':
        if len(save) == 0:
            print("student detail empty!!")
        else:
            print("student detail open!!")
            for i, student in enumerate(save, start=1):
                print(f"{i}. {student}")

    # DELETED STUDENT
    elif choice == '3':
        if len(save) == 0:
            print("student not delete!!")
        else:
            print("student detail!!")
            for i, student in enumerate(save, start=1):
                print(f"{i}. {student}")
            number = int(input("Enter student number:"))

            if 1 <= number <= len(save):
                removed = save.pop(number - 1)
                print(f"'{removed}' deleted successfully")
            else:
                print("invalid student number!!")

    # SEARCH STUDENT
    elif choice == '4':
        if len(save) == 0:
            print("student not found!!")
        else:
            search_name = input("Enter student name:")

            found = False

            for student in save:
                if student ["name"].lower() == search_name.lower():
                    print("student found!!")
                    print(student)
                    found = True
                    break
            if not found:
                print("student not found!!")

    # UPDATE STUDENT
    elif choice == '5':
        if len(save) == 0:
            print("student not found!!")
        else:
            print("student detail")
            for i, student in enumerate(save, start=1):
                print(f"{i}. {student}")
            number = int(input("Enter student number:"))
            if 1 <= number <= len(save):
                save[number - 1]["name"] = input("Enter new name:")
                save[number - 1]["school"] = input("Enter new school name:")
                save[number - 1]["age"] = input("Enter new age:")
                save[number - 1]["aim"] = input("Enter new aim:")
                print("student updated successfully")
            else:
                print("invalid student number!!")

    # EXIT THE PROJECT
    elif choice == '6':
        print("thanks for using student management detail project!!")
        break

    # INVALID CHOICE
    else:
        print("invalid choice!!")